### PR TITLE
fix broken named parameters for dlp.log_init

### PR DESCRIPTION
**Pull request by rayandrew**
[X] Fixed named parameters in `dlio_profiler/logger.py`
[X] Added test in `test/py/test.py`

### CODE REVIEW

**Comment by hariharan-devarajan** [comment]
@rayandrew Thanks a lot for the PR. The change looks good to me. 

Could u add the test on the CTest (https://github.com/hariharan-devarajan/dlio-profiler/blob/dev/test/CMakeLists.txt#L115) or just modify the existing test https://github.com/hariharan-devarajan/dlio-profiler/blob/dev/test/py/test.py to reflect this change. 

For the CTest, the idea is that we have a disabled test case and a hybrid case.

**Comment by rayandrew** [comment]
@hariharan-devarajan just want to make sure that I just need to remove my test file and add the code inside my test file to https://github.com/hariharan-devarajan/dlio-profiler/blob/dev/test/py/test.py right?

With that, I do not need to modify the CMakeLists but is it fine if the test file (https://github.com/hariharan-devarajan/dlio-profiler/blob/dev/test/py/test.py) consists of my test code as well?

Thanks!

**Comment by hariharan-devarajan** [comment]
Yes u can add that case in the test.py. and ensure it runs in the main function.

**Comment by rayandrew** [comment]
Hi @hariharan-devarajan, I just pushed new changes to accommodate your requests

**Comment by hariharan-devarajan** [comment]
@rayandrew The CI is failing. Looks like the args are not matching

`[DLIO_PROFILER_PY DEBUG] logger.initialize_log None None -1 [/home/runner/work/dlio-profiler/venv/lib/python3.10/site-packages/dlio_profiler/logger.py:71]
19: usage: DLIO testing [-h] [--data_dir DATA_DIR] [--format FORMAT]
19:                     [--num_files NUM_FILES] [--niter NITER]
19:                     [--record_size RECORD_SIZE]
19: DLIO testing: error: unrecognized arguments: --log_dir=/home/runner/work/dlio-profiler/dlio-profiler/build/temp.linux-x86_64-cpython-310/dlio_profiler.dlio_profiler_py/test/test_py_disable_only`

**Comment by hariharan-devarajan** [comment]
@rayandrew I fix the args and this works now. Thanks for the fix. I will approve and merge it now.

**Comment by rayandrew** [comment]
Ah my bad! Thanks @hariharan-devarajan!

**Pull request merged**
